[package]
name = "download-shell"
edition = "2024"
version = "1.0.0"
license = "GPL-2.0"
private = true

[dependencies]
libc = "0.2"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
